//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 09:03:07 AM EET 
//


package soap.client.soapclient.client;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.client.soapclient.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RgWsPublic2VersionInfo_QNAME = new QName("http://rgwspublic2/RgWsPublic2Service", "rgWsPublic2VersionInfo");
    private final static QName _RgWsPublic2VersionInfoResponse_QNAME = new QName("http://rgwspublic2/RgWsPublic2Service", "rgWsPublic2VersionInfoResponse");
    private final static QName _RgWsPublic2AfmMethod_QNAME = new QName("http://rgwspublic2/RgWsPublic2Service", "rgWsPublic2AfmMethod");
    private final static QName _RgWsPublic2AfmMethodResponse_QNAME = new QName("http://rgwspublic2/RgWsPublic2Service", "rgWsPublic2AfmMethodResponse");
    private final static QName _RgWsPublic2InputRtType_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "rg_ws_public2_input_rtType");
    private final static QName _GenWsErrorRtType_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "gen_ws_error_rtType");
    private final static QName _RgWsPublic2AfmCalledByRtType_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "rg_ws_public2_afm_called_by_rtType");
    private final static QName _RgWsPublic2BasicRtType_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "rg_ws_public2_basic_rtType");
    private final static QName _RgWsPublic2FirmActRtType_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "rg_ws_public2_firm_act_rtType");
    private final static QName _RgWsPublic2FirmActTtType_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "rg_ws_public2_firm_act_ttType");
    private final static QName _RgWsPublic2ResultRtType_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "rg_ws_public2_result_rtType");
    private final static QName _RgWsPublic2ResultRtTypeCallSeqId_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "call_seq_id");
    private final static QName _RgWsPublic2FirmActRtTypeFirmActCode_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "firm_act_code");
    private final static QName _RgWsPublic2FirmActRtTypeFirmActDescr_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "firm_act_descr");
    private final static QName _RgWsPublic2FirmActRtTypeFirmActKind_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "firm_act_kind");
    private final static QName _RgWsPublic2FirmActRtTypeFirmActKindDescr_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "firm_act_kind_descr");
    private final static QName _RgWsPublic2BasicRtTypeAfm_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "afm");
    private final static QName _RgWsPublic2BasicRtTypeDoy_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "doy");
    private final static QName _RgWsPublic2BasicRtTypeDoyDescr_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "doy_descr");
    private final static QName _RgWsPublic2BasicRtTypeINiFlagDescr_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "i_ni_flag_descr");
    private final static QName _RgWsPublic2BasicRtTypeDeactivationFlag_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "deactivation_flag");
    private final static QName _RgWsPublic2BasicRtTypeDeactivationFlagDescr_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "deactivation_flag_descr");
    private final static QName _RgWsPublic2BasicRtTypeFirmFlagDescr_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "firm_flag_descr");
    private final static QName _RgWsPublic2BasicRtTypeOnomasia_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "onomasia");
    private final static QName _RgWsPublic2BasicRtTypeCommerTitle_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "commer_title");
    private final static QName _RgWsPublic2BasicRtTypeLegalStatusDescr_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "legal_status_descr");
    private final static QName _RgWsPublic2BasicRtTypePostalAddress_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "postal_address");
    private final static QName _RgWsPublic2BasicRtTypePostalAddressNo_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "postal_address_no");
    private final static QName _RgWsPublic2BasicRtTypePostalZipCode_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "postal_zip_code");
    private final static QName _RgWsPublic2BasicRtTypePostalAreaDescription_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "postal_area_description");
    private final static QName _RgWsPublic2BasicRtTypeRegistDate_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "regist_date");
    private final static QName _RgWsPublic2BasicRtTypeStopDate_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "stop_date");
    private final static QName _RgWsPublic2BasicRtTypeNormalVatSystemFlag_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "normal_vat_system_flag");
    private final static QName _RgWsPublic2AfmCalledByRtTypeTokenUsername_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "token_username");
    private final static QName _RgWsPublic2AfmCalledByRtTypeTokenAfm_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "token_afm");
    private final static QName _RgWsPublic2AfmCalledByRtTypeTokenAfmFullname_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "token_afm_fullname");
    private final static QName _RgWsPublic2AfmCalledByRtTypeAfmCalledBy_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "afm_called_by");
    private final static QName _RgWsPublic2AfmCalledByRtTypeAfmCalledByFullname_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "afm_called_by_fullname");
    private final static QName _RgWsPublic2AfmCalledByRtTypeAsOnDate_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "as_on_date");
    private final static QName _GenWsErrorRtTypeErrorCode_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "error_code");
    private final static QName _GenWsErrorRtTypeErrorDescr_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "error_descr");
    private final static QName _RgWsPublic2InputRtTypeAfmCalledFor_QNAME = new QName("http://rgwspublic2/RgWsPublic2", "afm_called_for");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap.client.soapclient.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RgWsPublic2ResultRtType }
     * 
     */
    public RgWsPublic2ResultRtType createRgWsPublic2ResultRtType() {
        return new RgWsPublic2ResultRtType();
    }

    /**
     * Create an instance of {@link RgWsPublic2AfmMethodResponseType }
     * 
     */
    public RgWsPublic2AfmMethodResponseType createRgWsPublic2AfmMethodResponseType() {
        return new RgWsPublic2AfmMethodResponseType();
    }

    /**
     * Create an instance of {@link RgWsPublic2VersionInfoRequestType }
     * 
     */
    public RgWsPublic2VersionInfoRequestType createRgWsPublic2VersionInfoRequestType() {
        return new RgWsPublic2VersionInfoRequestType();
    }

    /**
     * Create an instance of {@link RgWsPublic2VersionInfoResponseType }
     * 
     */
    public RgWsPublic2VersionInfoResponseType createRgWsPublic2VersionInfoResponseType() {
        return new RgWsPublic2VersionInfoResponseType();
    }

    /**
     * Create an instance of {@link RgWsPublic2AfmMethodRequestType }
     * 
     */
    public RgWsPublic2AfmMethodRequestType createRgWsPublic2AfmMethodRequestType() {
        return new RgWsPublic2AfmMethodRequestType();
    }

    /**
     * Create an instance of {@link RgWsPublic2InputRtType }
     * 
     */
    public RgWsPublic2InputRtType createRgWsPublic2InputRtType() {
        return new RgWsPublic2InputRtType();
    }

    /**
     * Create an instance of {@link GenWsErrorRtType }
     * 
     */
    public GenWsErrorRtType createGenWsErrorRtType() {
        return new GenWsErrorRtType();
    }

    /**
     * Create an instance of {@link RgWsPublic2AfmCalledByRtType }
     * 
     */
    public RgWsPublic2AfmCalledByRtType createRgWsPublic2AfmCalledByRtType() {
        return new RgWsPublic2AfmCalledByRtType();
    }

    /**
     * Create an instance of {@link RgWsPublic2BasicRtType }
     * 
     */
    public RgWsPublic2BasicRtType createRgWsPublic2BasicRtType() {
        return new RgWsPublic2BasicRtType();
    }

    /**
     * Create an instance of {@link RgWsPublic2FirmActRtType }
     * 
     */
    public RgWsPublic2FirmActRtType createRgWsPublic2FirmActRtType() {
        return new RgWsPublic2FirmActRtType();
    }

    /**
     * Create an instance of {@link RgWsPublic2FirmActTtType }
     * 
     */
    public RgWsPublic2FirmActTtType createRgWsPublic2FirmActTtType() {
        return new RgWsPublic2FirmActTtType();
    }

    /**
     * Create an instance of {@link RgWsPublic2ResultRtType.FirmActTab }
     * 
     */
    public RgWsPublic2ResultRtType.FirmActTab createRgWsPublic2ResultRtTypeFirmActTab() {
        return new RgWsPublic2ResultRtType.FirmActTab();
    }

    /**
     * Create an instance of {@link RgWsPublic2AfmMethodResponseType.Result }
     * 
     */
    public RgWsPublic2AfmMethodResponseType.Result createRgWsPublic2AfmMethodResponseTypeResult() {
        return new RgWsPublic2AfmMethodResponseType.Result();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2VersionInfoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2Service", name = "rgWsPublic2VersionInfo")
    public JAXBElement<RgWsPublic2VersionInfoRequestType> createRgWsPublic2VersionInfo(RgWsPublic2VersionInfoRequestType value) {
        return new JAXBElement<RgWsPublic2VersionInfoRequestType>(_RgWsPublic2VersionInfo_QNAME, RgWsPublic2VersionInfoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2VersionInfoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2Service", name = "rgWsPublic2VersionInfoResponse")
    public JAXBElement<RgWsPublic2VersionInfoResponseType> createRgWsPublic2VersionInfoResponse(RgWsPublic2VersionInfoResponseType value) {
        return new JAXBElement<RgWsPublic2VersionInfoResponseType>(_RgWsPublic2VersionInfoResponse_QNAME, RgWsPublic2VersionInfoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2AfmMethodRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2Service", name = "rgWsPublic2AfmMethod")
    public JAXBElement<RgWsPublic2AfmMethodRequestType> createRgWsPublic2AfmMethod(RgWsPublic2AfmMethodRequestType value) {
        return new JAXBElement<RgWsPublic2AfmMethodRequestType>(_RgWsPublic2AfmMethod_QNAME, RgWsPublic2AfmMethodRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2AfmMethodResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2Service", name = "rgWsPublic2AfmMethodResponse")
    public JAXBElement<RgWsPublic2AfmMethodResponseType> createRgWsPublic2AfmMethodResponse(RgWsPublic2AfmMethodResponseType value) {
        return new JAXBElement<RgWsPublic2AfmMethodResponseType>(_RgWsPublic2AfmMethodResponse_QNAME, RgWsPublic2AfmMethodResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2InputRtType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "rg_ws_public2_input_rtType")
    public JAXBElement<RgWsPublic2InputRtType> createRgWsPublic2InputRtType(RgWsPublic2InputRtType value) {
        return new JAXBElement<RgWsPublic2InputRtType>(_RgWsPublic2InputRtType_QNAME, RgWsPublic2InputRtType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenWsErrorRtType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "gen_ws_error_rtType")
    public JAXBElement<GenWsErrorRtType> createGenWsErrorRtType(GenWsErrorRtType value) {
        return new JAXBElement<GenWsErrorRtType>(_GenWsErrorRtType_QNAME, GenWsErrorRtType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2AfmCalledByRtType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "rg_ws_public2_afm_called_by_rtType")
    public JAXBElement<RgWsPublic2AfmCalledByRtType> createRgWsPublic2AfmCalledByRtType(RgWsPublic2AfmCalledByRtType value) {
        return new JAXBElement<RgWsPublic2AfmCalledByRtType>(_RgWsPublic2AfmCalledByRtType_QNAME, RgWsPublic2AfmCalledByRtType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2BasicRtType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "rg_ws_public2_basic_rtType")
    public JAXBElement<RgWsPublic2BasicRtType> createRgWsPublic2BasicRtType(RgWsPublic2BasicRtType value) {
        return new JAXBElement<RgWsPublic2BasicRtType>(_RgWsPublic2BasicRtType_QNAME, RgWsPublic2BasicRtType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2FirmActRtType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "rg_ws_public2_firm_act_rtType")
    public JAXBElement<RgWsPublic2FirmActRtType> createRgWsPublic2FirmActRtType(RgWsPublic2FirmActRtType value) {
        return new JAXBElement<RgWsPublic2FirmActRtType>(_RgWsPublic2FirmActRtType_QNAME, RgWsPublic2FirmActRtType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2FirmActTtType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "rg_ws_public2_firm_act_ttType")
    public JAXBElement<RgWsPublic2FirmActTtType> createRgWsPublic2FirmActTtType(RgWsPublic2FirmActTtType value) {
        return new JAXBElement<RgWsPublic2FirmActTtType>(_RgWsPublic2FirmActTtType_QNAME, RgWsPublic2FirmActTtType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RgWsPublic2ResultRtType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "rg_ws_public2_result_rtType")
    public JAXBElement<RgWsPublic2ResultRtType> createRgWsPublic2ResultRtType(RgWsPublic2ResultRtType value) {
        return new JAXBElement<RgWsPublic2ResultRtType>(_RgWsPublic2ResultRtType_QNAME, RgWsPublic2ResultRtType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "call_seq_id", scope = RgWsPublic2ResultRtType.class)
    public JAXBElement<BigDecimal> createRgWsPublic2ResultRtTypeCallSeqId(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RgWsPublic2ResultRtTypeCallSeqId_QNAME, BigDecimal.class, RgWsPublic2ResultRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "firm_act_code", scope = RgWsPublic2FirmActRtType.class)
    public JAXBElement<BigDecimal> createRgWsPublic2FirmActRtTypeFirmActCode(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RgWsPublic2FirmActRtTypeFirmActCode_QNAME, BigDecimal.class, RgWsPublic2FirmActRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "firm_act_descr", scope = RgWsPublic2FirmActRtType.class)
    public JAXBElement<String> createRgWsPublic2FirmActRtTypeFirmActDescr(String value) {
        return new JAXBElement<String>(_RgWsPublic2FirmActRtTypeFirmActDescr_QNAME, String.class, RgWsPublic2FirmActRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "firm_act_kind", scope = RgWsPublic2FirmActRtType.class)
    public JAXBElement<String> createRgWsPublic2FirmActRtTypeFirmActKind(String value) {
        return new JAXBElement<String>(_RgWsPublic2FirmActRtTypeFirmActKind_QNAME, String.class, RgWsPublic2FirmActRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "firm_act_kind_descr", scope = RgWsPublic2FirmActRtType.class)
    public JAXBElement<String> createRgWsPublic2FirmActRtTypeFirmActKindDescr(String value) {
        return new JAXBElement<String>(_RgWsPublic2FirmActRtTypeFirmActKindDescr_QNAME, String.class, RgWsPublic2FirmActRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "afm", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeAfm(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeAfm_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "doy", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeDoy(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeDoy_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "doy_descr", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeDoyDescr(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeDoyDescr_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "i_ni_flag_descr", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeINiFlagDescr(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeINiFlagDescr_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "deactivation_flag", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeDeactivationFlag(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeDeactivationFlag_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "deactivation_flag_descr", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeDeactivationFlagDescr(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeDeactivationFlagDescr_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "firm_flag_descr", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeFirmFlagDescr(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeFirmFlagDescr_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "onomasia", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeOnomasia(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeOnomasia_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "commer_title", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeCommerTitle(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeCommerTitle_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "legal_status_descr", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeLegalStatusDescr(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeLegalStatusDescr_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "postal_address", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypePostalAddress(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypePostalAddress_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "postal_address_no", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypePostalAddressNo(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypePostalAddressNo_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "postal_zip_code", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypePostalZipCode(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypePostalZipCode_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "postal_area_description", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypePostalAreaDescription(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypePostalAreaDescription_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "regist_date", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<XMLGregorianCalendar> createRgWsPublic2BasicRtTypeRegistDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RgWsPublic2BasicRtTypeRegistDate_QNAME, XMLGregorianCalendar.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "stop_date", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<XMLGregorianCalendar> createRgWsPublic2BasicRtTypeStopDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RgWsPublic2BasicRtTypeStopDate_QNAME, XMLGregorianCalendar.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "normal_vat_system_flag", scope = RgWsPublic2BasicRtType.class)
    public JAXBElement<String> createRgWsPublic2BasicRtTypeNormalVatSystemFlag(String value) {
        return new JAXBElement<String>(_RgWsPublic2BasicRtTypeNormalVatSystemFlag_QNAME, String.class, RgWsPublic2BasicRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "token_username", scope = RgWsPublic2AfmCalledByRtType.class)
    public JAXBElement<String> createRgWsPublic2AfmCalledByRtTypeTokenUsername(String value) {
        return new JAXBElement<String>(_RgWsPublic2AfmCalledByRtTypeTokenUsername_QNAME, String.class, RgWsPublic2AfmCalledByRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "token_afm", scope = RgWsPublic2AfmCalledByRtType.class)
    public JAXBElement<String> createRgWsPublic2AfmCalledByRtTypeTokenAfm(String value) {
        return new JAXBElement<String>(_RgWsPublic2AfmCalledByRtTypeTokenAfm_QNAME, String.class, RgWsPublic2AfmCalledByRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "token_afm_fullname", scope = RgWsPublic2AfmCalledByRtType.class)
    public JAXBElement<String> createRgWsPublic2AfmCalledByRtTypeTokenAfmFullname(String value) {
        return new JAXBElement<String>(_RgWsPublic2AfmCalledByRtTypeTokenAfmFullname_QNAME, String.class, RgWsPublic2AfmCalledByRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "afm_called_by", scope = RgWsPublic2AfmCalledByRtType.class)
    public JAXBElement<String> createRgWsPublic2AfmCalledByRtTypeAfmCalledBy(String value) {
        return new JAXBElement<String>(_RgWsPublic2AfmCalledByRtTypeAfmCalledBy_QNAME, String.class, RgWsPublic2AfmCalledByRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "afm_called_by_fullname", scope = RgWsPublic2AfmCalledByRtType.class)
    public JAXBElement<String> createRgWsPublic2AfmCalledByRtTypeAfmCalledByFullname(String value) {
        return new JAXBElement<String>(_RgWsPublic2AfmCalledByRtTypeAfmCalledByFullname_QNAME, String.class, RgWsPublic2AfmCalledByRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "as_on_date", scope = RgWsPublic2AfmCalledByRtType.class)
    public JAXBElement<XMLGregorianCalendar> createRgWsPublic2AfmCalledByRtTypeAsOnDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RgWsPublic2AfmCalledByRtTypeAsOnDate_QNAME, XMLGregorianCalendar.class, RgWsPublic2AfmCalledByRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "error_code", scope = GenWsErrorRtType.class)
    public JAXBElement<String> createGenWsErrorRtTypeErrorCode(String value) {
        return new JAXBElement<String>(_GenWsErrorRtTypeErrorCode_QNAME, String.class, GenWsErrorRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "error_descr", scope = GenWsErrorRtType.class)
    public JAXBElement<String> createGenWsErrorRtTypeErrorDescr(String value) {
        return new JAXBElement<String>(_GenWsErrorRtTypeErrorDescr_QNAME, String.class, GenWsErrorRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "afm_called_by", scope = RgWsPublic2InputRtType.class)
    public JAXBElement<String> createRgWsPublic2InputRtTypeAfmCalledBy(String value) {
        return new JAXBElement<String>(_RgWsPublic2AfmCalledByRtTypeAfmCalledBy_QNAME, String.class, RgWsPublic2InputRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "afm_called_for", scope = RgWsPublic2InputRtType.class)
    public JAXBElement<String> createRgWsPublic2InputRtTypeAfmCalledFor(String value) {
        return new JAXBElement<String>(_RgWsPublic2InputRtTypeAfmCalledFor_QNAME, String.class, RgWsPublic2InputRtType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rgwspublic2/RgWsPublic2", name = "as_on_date", scope = RgWsPublic2InputRtType.class)
    public JAXBElement<XMLGregorianCalendar> createRgWsPublic2InputRtTypeAsOnDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RgWsPublic2AfmCalledByRtTypeAsOnDate_QNAME, XMLGregorianCalendar.class, RgWsPublic2InputRtType.class, value);
    }

}
