//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 09:03:07 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rgwspublic2/RgWsPublic2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap.client.soapclient.client;
