//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 09:03:07 AM EET 
//


package soap.client.soapclient.client;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rg_ws_public2_firm_act_rtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rg_ws_public2_firm_act_rtType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="firm_act_code" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="firm_act_descr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firm_act_kind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firm_act_kind_descr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rg_ws_public2_firm_act_rtType", propOrder = {
    "firmActCode",
    "firmActDescr",
    "firmActKind",
    "firmActKindDescr"
})
public class RgWsPublic2FirmActRtType {

    @XmlElementRef(name = "firm_act_code", namespace = "http://rgwspublic2/RgWsPublic2", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> firmActCode;
    @XmlElementRef(name = "firm_act_descr", namespace = "http://rgwspublic2/RgWsPublic2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> firmActDescr;
    @XmlElementRef(name = "firm_act_kind", namespace = "http://rgwspublic2/RgWsPublic2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> firmActKind;
    @XmlElementRef(name = "firm_act_kind_descr", namespace = "http://rgwspublic2/RgWsPublic2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> firmActKindDescr;

    /**
     * Gets the value of the firmActCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getFirmActCode() {
        return firmActCode;
    }

    /**
     * Sets the value of the firmActCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setFirmActCode(JAXBElement<BigDecimal> value) {
        this.firmActCode = value;
    }

    /**
     * Gets the value of the firmActDescr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFirmActDescr() {
        return firmActDescr;
    }

    /**
     * Sets the value of the firmActDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFirmActDescr(JAXBElement<String> value) {
        this.firmActDescr = value;
    }

    /**
     * Gets the value of the firmActKind property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFirmActKind() {
        return firmActKind;
    }

    /**
     * Sets the value of the firmActKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFirmActKind(JAXBElement<String> value) {
        this.firmActKind = value;
    }

    /**
     * Gets the value of the firmActKindDescr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFirmActKindDescr() {
        return firmActKindDescr;
    }

    /**
     * Sets the value of the firmActKindDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFirmActKindDescr(JAXBElement<String> value) {
        this.firmActKindDescr = value;
    }

}
