//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 09:03:07 AM EET 
//


package soap.client.soapclient.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rgWsPublic2AfmMethodResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rgWsPublic2AfmMethodResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="result"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://rgwspublic2/RgWsPublic2}rg_ws_public2_result_rtType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rgWsPublic2AfmMethodResponseType", namespace = "http://rgwspublic2/RgWsPublic2Service", propOrder = {
    "result"
})
public class RgWsPublic2AfmMethodResponseType {

    @XmlElement(required = true)
    protected RgWsPublic2AfmMethodResponseType.Result result;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link RgWsPublic2AfmMethodResponseType.Result }
     *     
     */
    public RgWsPublic2AfmMethodResponseType.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link RgWsPublic2AfmMethodResponseType.Result }
     *     
     */
    public void setResult(RgWsPublic2AfmMethodResponseType.Result value) {
        this.result = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://rgwspublic2/RgWsPublic2}rg_ws_public2_result_rtType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rgWsPublic2ResultRtType"
    })
    public static class Result {

        @XmlElement(name = "rg_ws_public2_result_rtType")
        protected RgWsPublic2ResultRtType rgWsPublic2ResultRtType;

        /**
         * Gets the value of the rgWsPublic2ResultRtType property.
         * 
         * @return
         *     possible object is
         *     {@link RgWsPublic2ResultRtType }
         *     
         */
        public RgWsPublic2ResultRtType getRgWsPublic2ResultRtType() {
            return rgWsPublic2ResultRtType;
        }

        /**
         * Sets the value of the rgWsPublic2ResultRtType property.
         * 
         * @param value
         *     allowed object is
         *     {@link RgWsPublic2ResultRtType }
         *     
         */
        public void setRgWsPublic2ResultRtType(RgWsPublic2ResultRtType value) {
            this.rgWsPublic2ResultRtType = value;
        }

    }

}
