//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 09:03:07 AM EET 
//


package soap.client.soapclient.client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for rg_ws_public2_input_rtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rg_ws_public2_input_rtType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="afm_called_by" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="afm_called_for" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="as_on_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rg_ws_public2_input_rtType", propOrder = {
    "afmCalledBy",
    "afmCalledFor",
    "asOnDate"
})
public class RgWsPublic2InputRtType {

    @XmlElementRef(name = "afm_called_by", namespace = "http://rgwspublic2/RgWsPublic2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> afmCalledBy;
    @XmlElementRef(name = "afm_called_for", namespace = "http://rgwspublic2/RgWsPublic2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> afmCalledFor;
    @XmlElementRef(name = "as_on_date", namespace = "http://rgwspublic2/RgWsPublic2", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> asOnDate;

    /**
     * Gets the value of the afmCalledBy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAfmCalledBy() {
        return afmCalledBy;
    }

    /**
     * Sets the value of the afmCalledBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAfmCalledBy(JAXBElement<String> value) {
        this.afmCalledBy = value;
    }

    /**
     * Gets the value of the afmCalledFor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAfmCalledFor() {
        return afmCalledFor;
    }

    /**
     * Sets the value of the afmCalledFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAfmCalledFor(JAXBElement<String> value) {
        this.afmCalledFor = value;
    }

    /**
     * Gets the value of the asOnDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getAsOnDate() {
        return asOnDate;
    }

    /**
     * Sets the value of the asOnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setAsOnDate(JAXBElement<XMLGregorianCalendar> value) {
        this.asOnDate = value;
    }

}
