//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.26 at 09:03:07 AM EET 
//


package soap.client.soapclient.client;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rg_ws_public2_result_rtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rg_ws_public2_result_rtType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="call_seq_id" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="error_rec" type="{http://rgwspublic2/RgWsPublic2}gen_ws_error_rtType"/&gt;
 *         &lt;element name="afm_called_by_rec" type="{http://rgwspublic2/RgWsPublic2}rg_ws_public2_afm_called_by_rtType"/&gt;
 *         &lt;element name="basic_rec" type="{http://rgwspublic2/RgWsPublic2}rg_ws_public2_basic_rtType"/&gt;
 *         &lt;element name="firm_act_tab"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="item" type="{http://rgwspublic2/RgWsPublic2}rg_ws_public2_firm_act_rtType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rg_ws_public2_result_rtType", propOrder = {
    "callSeqId",
    "errorRec",
    "afmCalledByRec",
    "basicRec",
    "firmActTab"
})
public class RgWsPublic2ResultRtType {

    @XmlElementRef(name = "call_seq_id", namespace = "http://rgwspublic2/RgWsPublic2", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> callSeqId;
    @XmlElement(name = "error_rec", required = true)
    protected GenWsErrorRtType errorRec;
    @XmlElement(name = "afm_called_by_rec", required = true)
    protected RgWsPublic2AfmCalledByRtType afmCalledByRec;
    @XmlElement(name = "basic_rec", required = true)
    protected RgWsPublic2BasicRtType basicRec;
    @XmlElement(name = "firm_act_tab", required = true)
    protected RgWsPublic2ResultRtType.FirmActTab firmActTab;

    /**
     * Gets the value of the callSeqId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getCallSeqId() {
        return callSeqId;
    }

    /**
     * Sets the value of the callSeqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setCallSeqId(JAXBElement<BigDecimal> value) {
        this.callSeqId = value;
    }

    /**
     * Gets the value of the errorRec property.
     * 
     * @return
     *     possible object is
     *     {@link GenWsErrorRtType }
     *     
     */
    public GenWsErrorRtType getErrorRec() {
        return errorRec;
    }

    /**
     * Sets the value of the errorRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenWsErrorRtType }
     *     
     */
    public void setErrorRec(GenWsErrorRtType value) {
        this.errorRec = value;
    }

    /**
     * Gets the value of the afmCalledByRec property.
     * 
     * @return
     *     possible object is
     *     {@link RgWsPublic2AfmCalledByRtType }
     *     
     */
    public RgWsPublic2AfmCalledByRtType getAfmCalledByRec() {
        return afmCalledByRec;
    }

    /**
     * Sets the value of the afmCalledByRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link RgWsPublic2AfmCalledByRtType }
     *     
     */
    public void setAfmCalledByRec(RgWsPublic2AfmCalledByRtType value) {
        this.afmCalledByRec = value;
    }

    /**
     * Gets the value of the basicRec property.
     * 
     * @return
     *     possible object is
     *     {@link RgWsPublic2BasicRtType }
     *     
     */
    public RgWsPublic2BasicRtType getBasicRec() {
        return basicRec;
    }

    /**
     * Sets the value of the basicRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link RgWsPublic2BasicRtType }
     *     
     */
    public void setBasicRec(RgWsPublic2BasicRtType value) {
        this.basicRec = value;
    }

    /**
     * Gets the value of the firmActTab property.
     * 
     * @return
     *     possible object is
     *     {@link RgWsPublic2ResultRtType.FirmActTab }
     *     
     */
    public RgWsPublic2ResultRtType.FirmActTab getFirmActTab() {
        return firmActTab;
    }

    /**
     * Sets the value of the firmActTab property.
     * 
     * @param value
     *     allowed object is
     *     {@link RgWsPublic2ResultRtType.FirmActTab }
     *     
     */
    public void setFirmActTab(RgWsPublic2ResultRtType.FirmActTab value) {
        this.firmActTab = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="item" type="{http://rgwspublic2/RgWsPublic2}rg_ws_public2_firm_act_rtType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class FirmActTab {

        @XmlElement(required = true)
        protected List<RgWsPublic2FirmActRtType> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RgWsPublic2FirmActRtType }
         * 
         * 
         */
        public List<RgWsPublic2FirmActRtType> getItem() {
            if (item == null) {
                item = new ArrayList<RgWsPublic2FirmActRtType>();
            }
            return this.item;
        }

    }

}
